---
- hosts: logstash-server
  
  tasks:

  - name: copy local sample data to remote
    copy: >
      src={{notebooks_home}}/sample_data/output_location_files.sh
      dest=~/output_location_files.sh