---
- hosts: logstash-server
  become: true
  
  tasks:

  - name: copy local main.conf to remote
    copy: >
      src={{notebooks_home}}/logstash_conf/main_networkport.conf
      dest=/etc/logstash/conf.d/main_networkport.conf
