---
- hosts: all
  become: true

  tasks:
  - name: install elasticsearch 6.1.3
    yum: 
      name: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.1.3.rpm
      state: present
